[package]
name = "rust_code"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_code"
crate-type = ["cdylib"] 

[dependencies]
rustfmt = "0.10.0"
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.24"
openssl-sys = { version = "0.9.110", features = ["vendored"] }
