name: "Unix s2n setup"
description: "Used to setup s2n in Unix"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        retry_on: error
        shell: bash
        command: |
          sudo apt-get update
          sudo apt-get install -y gcc make cmake
    - name: Build and Install s2n-tls
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        retry_on: error
        shell: bash
        command: |
          git clone https://github.com/awslabs/s2n.git
          cd s2n
          cmake .
          make
          sudo make install