name: "Unix llvm setup"
description: "Used to setup llvm in Unix"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        retry_on: error
        shell: bash
        command: |
          sudo apt-get update
          sudo apt-get install libgc-dev
    - name: Build and Install s2n-tls
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        retry_on: error
        shell: bash
        command: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          (yes "" || true) | sudo ./llvm.sh ${{ inputs.llvm-version }}